name: CI-CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]     # optionnel: pour tagger des releases v1.0.0
  pull_request:

permissions:
  contents: read
  packages: write   # nécessaire pour push sur GHCR

env:
  IMAGE_NAME: ci-cd-demo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build_scan_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à GHCR (registry GitHub)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Génère automatiquement les tags/labels (sha, branch, tag vX.Y.Z)
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Build image locally
        run: docker build -t ci-cd-demo:ci .

      - name: Trivy scan local image (fail on CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ci-cd-demo:ci
          scanners: vuln
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Trivy report (including HIGH) - non blocking
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ci-cd-demo:ci
          scanners: vuln
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Tag image for GHCR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker tag ci-cd-demo:ci ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

      - name: Push image to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}